name: seamless
channels:
    - conda-forge
    - pytorch
    - nvidia
dependencies:
    - numpy
    - shapely
    - scipy
    - scikit-image
    - pillow
    - pytorch
    - torchvision
    - pytorch-cuda=11.8
    - torchgeo
    - timm
